apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: "{{ template "neo4j.core.fullname" . }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "neo4j.name" . }}
    app.kubernetes.io/component: core
spec:
  podManagementPolicy: Parallel
  serviceName: {{ template "neo4j.fullname" . }}
  {{- if .Values.core.standalone }}
  replicas: 1
  {{- else }}
  replicas: {{ .Values.core.numberOfServers }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/name: {{ template "neo4j.name" . }}
      app.kubernetes.io/component: core
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app.kubernetes.io/name: {{ template "neo4j.name" . }}
        app.kubernetes.io/component: core
        {{-  range $key, $value := .Values.podLabels }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{-  range $key, $value := .Values.podAnnotations }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: "{{ template "neo4j.fullname" . }}-sa"
      # High value permits checkpointing on Neo4j shutdown.  See: https://neo4j.com/developer/kb/checkpointing-and-log-pruning-interactions/
      terminationGracePeriodSeconds: 300
      containers:
      - name: {{ template "neo4j.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        envFrom:
          - configMapRef:
              name: {{ template "neo4j.commonConfig.fullname" . }}
          - configMapRef:
              name: {{ template "neo4j.coreConfig.fullname" . }}
          {{- if .Values.core.configMap }}
          - configMapRef:
              name: "{{ .Values.core.configMap }}"
          {{- end }}
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: JVM_INITIAL_HEAP
            value: 512m
          - name: JVM_MAXIMUM_HEAP
            value: 512m
          - name: NEO4J_dbms_memory_pagecache_size
            value: 512m
          - name: NEO4J_dbms_connector_https_enabled
            value: 'false'
          - name: NEO4J_dbms_default__advertised__address
            value: $(HOSTNAME)
          - name: NEO4J_dbms_connector_bolt_advertised__address
            value: $(HOSTNAME):7687
          - name: NEO4J_dbms_connector_http_advertised__address
            value: $(HOSTNAME):7474
          - name: NEO4J_dbms_connector_https_advertised__address
            value: $(HOSTNAME):7473
          {{- if not .Values.core.standalone }}
          - name: NEO4J_causal__clustering_discovery__type
            value: K8S
          - name: DISCOVERY_HOST
            value: discovery-$(HOSTNAME).{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
          - name: NEO4J_causal__clustering_discovery__advertised__address
            value: $(DISCOVERY_HOST):5000
          - name: NEO4J_causal__clustering_transaction__advertised__address
            value: $(DISCOVERY_HOST):6000
          - name: NEO4J_causal__clustering_raft__advertised__address
            value: $(DISCOVERY_HOST):7000
          - name: NEO4J_causal__clustering_kubernetes_label__selector
            value: neo4j.com/cluster={{ template "neo4j.fullname" . }},neo4j.com/role=CORE,neo4j.com/coreindex in (0, 1, 2)
          - name: NEO4J_causal__clustering_kubernetes_service__port__name
            value: tcp-discovery
          {{- end }}
        ports:
        - containerPort: 5000
          name: tcp-discovery
        - containerPort: 7000
          name: tcp-raft
        - containerPort: 6000
          name: tcp-tx
        - containerPort: 7474
          name: tcp-browser
        - containerPort: 7687
          name: tcp-bolt
        {{- if .Values.metrics.prometheus.enabled }}
        - containerPort: 2004
          name: tcp-prometheus
        {{- end }}
        {{- if .Values.metrics.graphite.enabled }}
        - containerPort: 2003
          name: tcp-graphite
        {{- end }}
        {{- if .Values.metrics.jmx.enabled }}
        - containerPort: 3637
          name: tcp-jmx
        {{- end }}
        volumeMounts:
        - name: init-script
          mountPath: /helm-init
        - name: datadir
          mountPath: "{{ .Values.core.persistentVolume.mountPath }}"
          {{- if .Values.core.persistentVolume.subPath }}
          subPath: {{ .Values.core.persistentVolume.subPath }}
          {{- end }}
        - name: plugins
          mountPath: /plugins
        {{- if .Values.restoreSecret }}
        - name: creds
          mountPath: /auth
          readOnly: true
        {{- end }}
        {{- if .Values.core.additionalVolumeMounts }}
{{ toYaml .Values.core.additionalVolumeMounts | indent 8}}
        {{- end }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.core.sidecarContainers }}
{{ toYaml .Values.core.sidecarContainers | indent 6 }}
{{- end }}
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
{{- end -}}
{{- if .Values.core.initContainers }}
      initContainers:
{{ toYaml .Values.core.initContainers | indent 6 }}
{{- end }}
      volumes:
        - name: init-script
          configMap:
            name: "{{ .Release.Name }}-init-script"
        {{- if .Values.restoreSecret }}
        - name: creds
          secret:
            secretName: {{ .Values.restoreSecret }}
            items:
            - key: credentials.json
              path: credentials.json
        {{- end }}
        {{- if not .Values.core.persistentVolume.enabled }}
        - name: datadir
          emptyDir: {}
        {{- end }}
        - name: plugins
          emptyDir: {}
        {{- if .Values.core.additionalVolumes }}
{{ toYaml .Values.core.additionalVolumes | indent 8}}
        {{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
  {{- if .Values.core.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
        {{- if .Values.core.persistentVolume.annotations }}
{{ toYaml .Values.core.persistentVolume.annotations | indent 12 }}
        {{- end }}
      spec:
        accessModes:
          - ReadWriteOnce
      {{- if .Values.core.persistentVolume.storageClass }}
      {{- if (eq "-" .Values.core.persistentVolume.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.core.persistentVolume.storageClass }}"
      {{- end }}
      {{- end }}
        resources:
          requests:
            storage: "{{ .Values.core.persistentVolume.size }}"
  {{- end }}
