{{- if not .Values.core.standalone }}
# The ReadReplica deployment only happens for clustered installs.
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: "{{ template "neo4j.replica.fullname" . }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "neo4j.name" . }}
    app.kubernetes.io/component: replica
spec:
  podManagementPolicy: Parallel
  serviceName: "{{ template "neo4j.replica.fullname" . }}"
{{- if not .Values.readReplica.autoscaling.enabled }}
  replicas: {{ .Values.readReplica.numberOfServers }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "neo4j.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: replica
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app.kubernetes.io/name: {{ template "neo4j.name" . }}
        app.kubernetes.io/component: replica
        {{-  range $key, $value := .Values.podLabels }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{-  range $key, $value := .Values.podAnnotations }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: "{{ template "neo4j.fullname" . }}-sa"
      # High value permits checkpointing on Neo4j shutdown.  See: https://neo4j.com/developer/kb/checkpointing-and-log-pruning-interactions/
      terminationGracePeriodSeconds: 300
      containers:
      - name: neo4j
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        # Most pod config is factored into a different configMap, which is user overrideable.
        envFrom:
          - configMapRef:
              name: {{ template "neo4j.commonConfig.fullname" . }}
          - configMapRef:
              name: {{ template "neo4j.replicaConfig.fullname" . }}
          {{- if .Values.readReplica.configMap }}
          - configMapRef:
              name: "{{ .Values.readReplica.configMap }}"
          {{- end }}
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ADVERTISED_HOST
            value: $(HOSTNAME).{{ template "neo4j.fullname" . }}-replica.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
          - name: NEO4J_dbms_connector_https_enabled
            value: 'false'
          - name: NEO4J_dbms_default__advertised__address
            value: $(ADVERTISED_HOST)
          - name: NEO4J_dbms_connector_bolt_advertised__address
            value: $(ADVERTISED_HOST):7687
          - name: NEO4J_dbms_connector_http_advertised__address
            value: $(ADVERTISED_HOST):7474
          - name: NEO4J_dbms_connector_https_advertised__address
            value: $(ADVERTISED_HOST):7473
          - name: NEO4J_causal__clustering_discovery__type
            value: K8S
          - name: NEO4J_causal__clustering_discovery__advertised__address
            value: $(ADVERTISED_HOST):5000
          - name: NEO4J_causal__clustering_transaction__advertised__address
            value: $(ADVERTISED_HOST):6000
          - name: NEO4J_causal__clustering_raft__advertised__address
            value: $(ADVERTISED_HOST):7000
          - name: NEO4J_causal__clustering_kubernetes_label__selector
            value: neo4j.com/cluster={{ template "neo4j.fullname" . }},neo4j.com/role=CORE,neo4j.com/coreindex in (0, 1, 2)
          - name: NEO4J_causal__clustering_kubernetes_service__port__name
            value: tcp-discovery
        ports:
        - containerPort: 5000
          name: tcp-discovery
        - containerPort: 7000
          name: tcp-raft
        - containerPort: 6000
          name: tcp-tx
        - containerPort: 7474
          name: tcp-browser
        - containerPort: 7687
          name: tcp-bolt
        {{- if .Values.metrics.prometheus.enabled }}
        - containerPort: 2004
          name: tcp-prometheus
        {{- end }}
        {{- if .Values.metrics.graphite.enabled }}
        - containerPort: 2003
          name: tcp-graphite
        {{- end }}
        {{- if .Values.metrics.jmx.enabled }}
        - containerPort: 3637
          name: tcp-jmx
        {{- end }}
        volumeMounts:
        - name: plugins
          mountPath: /plugins
        - name: datadir
          mountPath: "{{ .Values.readReplica.persistentVolume.mountPath }}"
          {{- if .Values.readReplica.persistentVolume.subPath }}
          subPath: {{ .Values.readReplica.persistentVolume.subPath }}
          {{- end }}
        {{- if .Values.restoreSecret }}
        - name: creds
          mountPath: /auth
          readOnly: true
        {{- end }}
        {{- if .Values.readReplica.additionalVolumeMounts }}
{{ toYaml .Values.readReplica.additionalVolumeMounts | indent 8}}
        {{- end }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        resources:
{{ toYaml .Values.readReplica.resources | indent 10 }}
{{- if .Values.core.sidecarContainers }}
{{ toYaml .Values.core.sidecarContainers | indent 6 }}
{{- end }}
{{- if .Values.readReplica.initContainers }}
      initContainers:
{{ toYaml .Values.readReplica.initContainers | indent 6 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      volumes:
        {{- if .Values.restoreSecret }}
        - name: creds
          secret:
            secretName: {{ .Values.restoreSecret }}
            items:
            - key: credentials.json
              path: credentials.json
        {{- end }}
        {{- if not .Values.readReplica.persistentVolume.enabled }}
        - name: datadir
          emptyDir: {}
        {{- end }}
        - name: plugins
          emptyDir: {}
        {{- if .Values.readReplica.additionalVolumes }}
{{ toYaml .Values.readReplica.additionalVolumes | indent 8}}
        {{- end }}
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
{{- end -}}
  {{- if .Values.readReplica.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
        {{- if .Values.readReplica.persistentVolume.annotations }}
  {{ toYaml .Values.readReplica.persistentVolume.annotations | indent 12 }}
        {{- end }}
      spec:
        accessModes:
          - ReadWriteOnce
      {{- if .Values.readReplica.persistentVolume.storageClass }}
      {{- if (eq "-" .Values.readReplica.persistentVolume.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.readReplica.persistentVolume.storageClass }}"
      {{- end }}
      {{- end }}
        resources:
          requests:
            storage: "{{ .Values.readReplica.persistentVolume.size }}"
  {{- end }}
{{- end }} # if not standalone mode
